#ifndef CONSTANTS_H
#define CONSTANTS_H

#define WM_UPDATE_PIXELS (WM_USER + 1)

#define HEIGHT 480
#define WIDTH 854

#define BG_COLOR_FLOOR 0x1B231B
#define BG_COLOR 0x222425
#define GRAPHING_COLOR 0x2d4d64
#define AXIS_COLOR 0xFFFFFF
#define AXIS_ANNOTATIONS_COLOR 0xFFFFFF
#define WAVE_READING_COLOR_CH_A 0xDBDE64
#define WAVE_READING_COLOR_CH_B 0xA9E27F

#define GLOBAL_X_MARGIN 20
#define GLOBAL_Y_MARGIN 50

#define LINE_WIDTH 2

#define SCREEN_REFRESH_DELAY 1000 // milliseconds

#endif
